source 'https://rubygems.org'

ruby '2.7.7'

gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'sqlite3', '~> 1.4'
gem 'active_model_serializers', '~> 0.10.12'

group :development, :test do
  gem 'pry-rails', '~> 0.3.9'
end

group :test do
  gem 'rspec-rails', '~> 5.0.0'
  gem 'factory_bot_rails', '~> 6.2.0'
end
